#+TITLE: shell-babel
#+DATE: <2013-08-31 Sat>
#+AUTHOR: Derek Feichtinger
#+EMAIL: derek.feichtinger@psi.ch
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not LOGBOOK) date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: Emacs 24.3.1 (Org mode 8.0.7)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

* using a table as input

  We first create a table from a lisp list of lists. Since my final result table
  should contain three columns, I already insert a header row with the names for
  the three columns.
  #+BEGIN_SRC emacs-lisp :results value :exports both
    (cons '(col1 col2 col3)
          (loop for i from 5 to 15 collect `(,i ,(* i 5))))
  #+END_SRC

  #+NAME: table1
  #+RESULTS:
  | col1 | col2 | col3 |
  |    5 |   25 |      |
  |    6 |   30 |      |
  |    7 |   35 |      |
  |    8 |   40 |      |
  |    9 |   45 |      |
  |   10 |   50 |      |
  |   11 |   55 |      |
  |   12 |   60 |      |
  |   13 |   65 |      |
  |   14 |   70 |      |
  |   15 |   75 |      |

  sidenote: the -n flag results in line numbers for the exported source code.

  #+NAME: src-table2
  #+BEGIN_SRC sh -n :results value :exports both :var tbl=table1 :colnames yes
    while read a b rest; do
        echo $a $b $((b*2))
    done < <(echo "$tbl")
    
  #+END_SRC

  #+RESULTS:
  | col1 | col2 | col3 |
  |------+------+------|
  |    5 |   25 |   50 |
  |    6 |   30 |   60 |
  |    7 |   35 |   70 |
  |    8 |   40 |   80 |
  |    9 |   45 |   90 |
  |   10 |   50 |  100 |
  |   11 |   55 |  110 |
  |   12 |   60 |  120 |
  |   13 |   65 |  130 |
  |   14 |   70 |  140 |
  |   15 |   75 |  150 |

  One can use a slice indexing for only importing a subrange of a table
  #+BEGIN_SRC sh :results value :exports both :var slice=src-table2[3:10,0:1] :colnames yes
  echo $slice
  #+END_SRC

  #+RESULTS:
  : 7 35 8 40 9 45 10 50 11 55 12 60 13 65

* additionally supported options
** dir
   One can use the :dir option to have the shell code executed within 
   a particular working directory.

   #+BEGIN_SRC sh :results value :dir /home :exports both
   pwd
   #+END_SRC

   #+RESULTS:
   : /home

   Since the directory can also be a TRAMP URL, this :dir allows easy
   *execution of commands on remote servers*, which to me is the most
   powerful application of this option. Combine this option with
   the SSH configuration options *ControlMaster and ProxyCommand* to
   tunnel all connections through an initial control connection (without having
   to authenticate each time) and to jump through multiple hops.
  

   #+BEGIN_SRC sh :results raw drawer :dir /ssh:root@dftest2.psi.ch:/etc :exports both
   hostname
   pwd
   #+END_SRC

   #+RESULTS:
   :RESULTS:
   dftest2
   /etc
   :END:

* TODO noweb example
  Redefine noweb markers, since =<<= and =>>= are valid shell code redirectors.

* COMMENT babel settings
  
  Local Variables:
  org-babel-sh-command: "/bin/bash"
  org-babel-noweb-wrap-start: "{{{"
  org-babel-noweb-wrap-end: "}}}"
  org-confirm-babel-evaluate: nil
  org-export-babel-evaluate: nil
  End:
