#+TITLE: README
#+DATE: <2015-06-16 Tue>
#+AUTHOR: Derek Feichtinger
#+EMAIL: derek.feichtinger@psi.ch
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: Emacs 24.5.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

This is my collection of example documents to demonstrate the usage of org-babel
with different languages.

I have used org and especially the org-babel functionality for writing manuals for
- writing documentation for programming projects (e.g. for python)
- for documenting benchmarking tests
- documenting the installation of servers. E.g. the complete installation of
  an OpenLDAP master and its slaves is an executable document. By making smart
  use of tramp + ssh configuration, the code is executed on the servers a
  few hops away. The documentation I publish via my Twiki exporter on our
  intranet
- creating OpenDocument documents from clean templates
- Planning a major (17 people project) using org tables and lisp code for
  more complex table functions. The cost planning and general planning
  was all done in org. The project's gantt chart had to be done in MS Project
  due to our institution's guidelines, but based on the MS Project csv export,
  I can process the MS project data again directly in org. This made the committing
  of changes into the evolving proposal a breeze!
- ...

I again have to thank the authors and maintainers of org-mode and all the community for
providing such a versatile and efficient tool. I hope that others can profit from
the examples. Sometimes it took quite a bit to understand how to do certain things,
and I was glad to find references.

I am glad for feedback and corrections.

Have fun hacking away....
Derek
